<a href="https://colab.research.google.com/github/Vishal-Mungal/NNDLPRACTICAL/blob/main/practical1nndl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [11]:
vec_a=np.array([1,2,3])
vec_b=np.array([4,5,6])
vec_sum=vec_a+vec_b
print(vec_sum)
print(np.add(vec_a,vec_b))

[5 7 9]
[5 7 9]


In [4]:
print("hello student")

hello student


In [12]:
#matrix multiplication
#define 2*3 matrix (matrix x) & a 3*2 matrix (matrix y)
matrix_x=np.array([[1,2,3],[4,5,6]])
matrix_y=np.array([[7,8,9],[10,11,12],[12,13,14]])
print(np.matmul(mat1,mat2))

[[ 63  69  75]
 [150 165 180]]
