<a href="https://colab.research.google.com/github/Vishal-Mungal/NNDLPRACTICAL/blob/main/practical1nndl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
vector1=([1,2,3])
vector2=([4,5,6])
print(np.add(vector1,vector2))

[5 7 9]


In [4]:
print("hello student")

hello student


In [7]:
mat1=np.array([[1,2,3],[4,5,6]])
mat2=np.array([[7,8,9],[10,11,12],[12,13,14]])
print(np.matmul(mat1,mat2))

[[ 63  69  75]
 [150 165 180]]
